/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author ASUS
 */
public class Finish extends javax.swing.JFrame {

    /**
     * Creates new form Finish
     */
    public static double waktuKembali;

    public Finish() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jLabel3.setBackground(new java.awt.Color(248, 237, 238));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 237, 238));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter the number of dresses");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 112, 123));

        jLabel4.setBackground(new java.awt.Color(245, 112, 123));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 241, 250));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thank you for renting");

        jLabel5.setBackground(new java.awt.Color(248, 237, 238));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 237, 238));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter the number of returning days");

        jLabel6.setBackground(new java.awt.Color(248, 237, 238));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 237, 238));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Detail's rent");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(101, 101, 101).addComponent(jTextField1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(179, 179, 179).addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel1Layout.createSequentialGroup().addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2).addComponent(jScrollPane1)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(70, 70, 70)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addGap(23, 23, 23)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton1)
                        .addGap(31, 31, 31).addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        waktuKembali = Double.parseDouble(jTextField1.getText());
        if (Kategori.categoryClothes == "Gaun") {
            if (Dress.namaGaun == "Sweet Heart Gown") {
                SewaGaun SH = new SewaGaun(Welcome.namaPenyewa, Dress.namaGaun, Dress.hargaSewa, Dress.ukuranPinggang,
                        Dress.ukuranDada, Dress.ukuranPinggul, WarnaJumlahDress.stok, WarnaJumlahDress.jumlah,
                        WarnaJumlahDress.warnaGaun);
                SH.setWaktuSewa(Welcome.waktuSewa);
                SH.setWatkuKembali(waktuKembali);

                SH.sewa();
                SH.detailinfo();

                jTextArea1.setText("\n Name \t : " + Welcome.namaPenyewa + "\n Dress \t : " + Dress.namaGaun
                        + "\n Bust \t : " + Dress.ukuranDada + "\n Waist \t : " + Dress.ukuranPinggang + "\n Hips \t : "
                        + Dress.ukuranPinggul + "\n Color \t : " + WarnaJumlahDress.warnaGaun + "\n Quantity \t : "
                        + WarnaJumlahDress.jumlah + "\n Price/day \t : " + Dress.hargaSewa + "\n Day's rent \t : "
                        + Welcome.waktuSewa + "\n Day's return \t : " + waktuKembali + "\n Total \t : "
                        + SH.totalBayar);

            } else if (Dress.namaGaun == "Tiffany Liem") {
                SewaGaun TL = new SewaGaun(Welcome.namaPenyewa, Dress.namaGaun, Dress.hargaSewa, Dress.ukuranPinggang,
                        Dress.ukuranDada, Dress.ukuranPinggul, WarnaJumlahDress.stok, WarnaJumlahDress.jumlah,
                        WarnaJumlahDress.warnaGaun);
                TL.setWaktuSewa(Welcome.waktuSewa);
                TL.setWatkuKembali(waktuKembali);
                TL.sewa();
                TL.detailinfo();

                jTextArea1.setText("\n Name \t : " + Welcome.namaPenyewa + "\n Dress \t : " + Dress.namaGaun
                        + "\n Bust \t : " + Dress.ukuranDada + "\n Waist \t : " + Dress.ukuranPinggang + "\n Hips \t : "
                        + Dress.ukuranPinggul + "\n Color \t : " + WarnaJumlahDress.warnaGaun + "\n Quantity \t : "
                        + WarnaJumlahDress.jumlah + "\n Price/day \t : " + Dress.hargaSewa + "\n Day's rent \t : "
                        + Welcome.waktuSewa + "\n Day's return \t : " + waktuKembali + "\n Total \t : "
                        + TL.totalBayar);
            }

            if (waktuKembali > Welcome.waktuSewa) {
                double hariDenda = waktuKembali - Welcome.waktuSewa;
                double denda = (hariDenda * Dress.hargaSewa) + 50000;
                jTextArea2.setText("\n Status \t : Late" + "\n Fine \t : " + denda);
            } else {
                jTextArea2.setText("\n Status \t : On time" + "\n Fine \t : -");
            }

        } else {
            if (Kategori2.category == "Halloween") {
                if (Halloween.namaKostum == "Vampire") {
                    SewaKostum Vampire = new SewaKostum(Welcome.namaPenyewa, Halloween.namaKostum,
                            Halloween.ukuranKostum, Halloween.hargaSewa, JumlahKostum.stok, JumlahKostum.jumlah,
                            Kategori2.category);
                    Vampire.setWaktuSewa(Welcome.waktuSewa);
                    Vampire.setWatkuKembali(waktuKembali);
                    Vampire.sewa("pbo");
                    Vampire.detailinfo();

                    jTextArea1.setText("\n Name \t : " + Welcome.namaPenyewa + "\n Costume \t : " + Halloween.namaKostum
                            + "\n Ukuran \t : " + Halloween.ukuranKostum + "\n Category \t : " + Kategori2.category
                            + "\n Quantity \t : " + JumlahKostum.jumlah + "\n Price/day \t : " + Halloween.hargaSewa
                            + "\n Day's rent \t : " + Welcome.waktuSewa + "\n Day's return \t : " + waktuKembali
                            + "\n Total \t : " + Vampire.totalBayar);
                } else {
                    SewaKostum AB = new SewaKostum(Welcome.namaPenyewa, Halloween.namaKostum, Halloween.ukuranKostum,
                            Halloween.hargaSewa, JumlahKostum.stok, JumlahKostum.jumlah, Kategori2.category);
                    AB.setWaktuSewa(Welcome.waktuSewa);
                    AB.setWatkuKembali(waktuKembali);
                    AB.sewa();
                    AB.detailinfo();

                    jTextArea1.setText("\n Name \t : " + Welcome.namaPenyewa + "\n Costume \t : " + Halloween.namaKostum
                            + "\n Ukuran \t : " + Halloween.ukuranKostum + "\n Category \t : " + Kategori2.category
                            + "\n Quantity \t : " + JumlahKostum.jumlah + "\n Price/day \t : " + Halloween.hargaSewa
                            + "\n Day's rent \t : " + Welcome.waktuSewa + "\n Day's return \t : " + waktuKembali
                            + "\n Total \t : " + AB.totalBayar);
                }

                if (waktuKembali > Welcome.waktuSewa) {
                    double hariDenda = waktuKembali - Welcome.waktuSewa;
                    double denda = (hariDenda * Halloween.hargaSewa) + 50000;
                    jTextArea2.setText("\n Status \t : Late" + "\n Fine \t : " + denda);
                } else {
                    jTextArea2.setText("\n Status \t : On time" + "\n Fine \t : -");
                }

            } else {
                if (Avenger.namaKostum == "Wonder Women") {
                    SewaKostum WW = new SewaKostum(Welcome.namaPenyewa, Avenger.namaKostum, Avenger.ukuranKostum,
                            Avenger.hargaSewa, JumlahKostum.stok, JumlahKostum.jumlah, Kategori2.category);
                    WW.setWaktuSewa(Welcome.waktuSewa);
                    WW.setWatkuKembali(waktuKembali);
                    WW.sewa();
                    WW.detailinfo();

                    jTextArea1.setText("\n Name \t : " + Welcome.namaPenyewa + "\n Costume \t : " + Avenger.namaKostum
                            + "\n Ukuran \t : " + Avenger.ukuranKostum + "\n Category \t : " + Kategori2.category
                            + "\n Quantity \t : " + JumlahKostum.jumlah + "\n Price/day \t : " + Avenger.hargaSewa
                            + "\n Day's rent \t : " + Welcome.waktuSewa + "\n Day's return \t : " + waktuKembali
                            + "\n Total \t : " + WW.totalBayar);
                } else {
                    SewaKostum IM = new SewaKostum(Welcome.namaPenyewa, Avenger.namaKostum, Avenger.ukuranKostum,
                            Avenger.hargaSewa, JumlahKostum.stok, JumlahKostum.jumlah, Kategori2.category);
                    IM.setWaktuSewa(Welcome.waktuSewa);
                    IM.setWatkuKembali(waktuKembali);
                    IM.sewa();
                    IM.detailinfo();

                    jTextArea1.setText("\n Name \t : " + Welcome.namaPenyewa + "\n Costume \t : " + Avenger.namaKostum
                            + "\n Ukuran \t : " + Avenger.ukuranKostum + "\n Category \t : " + Kategori2.category
                            + "\n Quantity \t : " + JumlahKostum.jumlah + "\n Price/day \t : " + Avenger.hargaSewa
                            + "\n Day's rent \t : " + Welcome.waktuSewa + "\n Day's return \t : " + waktuKembali
                            + "\n Total \t : " + IM.totalBayar);
                }

                if (waktuKembali > Welcome.waktuSewa) {
                    double hariDenda = waktuKembali - Welcome.waktuSewa;
                    double denda = (hariDenda * Avenger.hargaSewa) + 50000;
                    jTextArea2.setText("\n Status \t : Late" + "\n Fine \t : " + denda);
                } else {
                    jTextArea2.setText("\n Status \t : On time" + "\n Fine \t : -");
                }
            }
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
